### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by fredix** [0xflux/bloggr#6]
Hi @0xflux ,
I'm afraid because I made a sort of fork of bloggr for my personal project [Gibson](https://codeberg.org/fredix/gibson).
So thanks for bloggr which permit me to launch my project, I modified many of your code, but I keep some of them...
I know I had should ask before, but I hope it's not to late, So do you plan to use a Free license to Bloggr ?

**Comment by 0xflux** [comment]
Hey @fredix - feel free to use the code as you wish, I'll add a licence :)

I'll add the MIT License - you may do as you please with the source code :)

**Comment by 0xflux** [comment]
https://github.com/0xflux/bloggr/blob/main/LICENSE

**Comment by fredix** [comment]
Hey @0xflux ,
many many thanks for your Free license choice :)
and thanks again for your project which helped me a lot to start mine.

**Comment by 0xflux** [comment]
Good luck with your project! 🥳
